// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-facing album metadata (the abstract level). Empty fields are not
 * written. All fields may contain macros.
 */
export type AlbumMeta = { album: string, 
/**
 * Album-level artist ("Album artist" in players).
 */
album_artist: string, 
/**
 * Track artist; defaults to the album artist when empty.
 */
artist: string, 
/**
 * Free-form date ("2026", "2026-08-01"…). The year is derived from the
 * first 4 digits for formats that want a separate year field.
 */
date: string, genre: string, comment: string, 
/**
 * Track numbers (1-based, in playing order) that START a new disc.
 * Empty = single disc. Example: [7, 13] → tracks 1-6 = disc 1,
 * 7-12 = disc 2, 13+ = disc 3.
 */
disc_breaks: Array<number>, };
