// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AlbumTrack = { 
/**
 * Region id (stable key).
 */
id: number, number: number, title: string, 
/**
 * Start position in ALBUM time (samples at the session rate).
 */
start_sample: number, length_samples: number, 
/**
 * Resolved gap before this track (0 for track 1), in ms.
 */
gap_before_ms: number, };
