// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlbumTrack } from "./AlbumTrack";

export type AlbumLayout = { tracks: Array<AlbumTrack>, total_samples: number, };
