// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One installed effect component, as shown in the plugin browser.
 */
export type AuComponentInfo = { 
/**
 * Stable identifier "type:subtype:manufacturer" (fourcc strings).
 */
id: string, name: string, };
