// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipInfo } from "./ClipInfo";
import type { ScannedLayer } from "./ScannedLayer";

export type AudioInfo = { 
/**
 * First clip's path of the base layer (display/naming convenience).
 */
path: string, 
/**
 * Base layer's clips (timeline boundaries shown in the UI).
 */
clips: Array<ClipInfo>, 
/**
 * All layers, in order (index-aligned with the project's layer list).
 */
layers: Array<ScannedLayer>, 
/**
 * Total timeline length (longest layer).
 */
duration_samples: number, sample_rate: number, 
/**
 * Session channel count (max over layers).
 */
channels: number, 
/**
 * Display string, e.g. "FLAC".
 */
format: string, duration_seconds: number, };
