// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipInfo } from "./ClipInfo";

export type AudioInfo = { 
/**
 * First clip's path (kept for display/naming convenience).
 */
path: string, 
/**
 * Ordered clips forming the timeline.
 */
clips: Array<ClipInfo>, 
/**
 * Total timeline length.
 */
duration_samples: number, sample_rate: number, channels: number, 
/**
 * Display string, e.g. "FLAC".
 */
format: string, duration_seconds: number, };
