// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A plugin chain's owner: the master bus, one layer (pre-fader, always
 * active) or one track (master-bus position, active inside its span).
 */
export type ChainTarget = { "kind": "master" } | { "kind": "layer", id: number, } | { "kind": "track", id: number, };
