// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Listing entry sent to the frontend.
 */
export type ChainPresetInfo = { name: string, 
/**
 * Plugin display names, in chain order.
 */
plugins: Array<string>, };
