// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One source file placed on the session timeline. Clips are laid out
 * back-to-back in order; all positions are timeline samples.
 */
export type ClipInfo = { path: string, 
/**
 * File name (display).
 */
name: string, 
/**
 * Timeline position of the clip's first sample.
 */
start_sample: number, duration_samples: number, };
