// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dither applied when reducing bit depth on lossless output. `Auto`
 * picks triangular_hp whenever the output is 16-bit; `Off` truncates
 * (only correct when no depth reduction happens). Lossy outputs never
 * dither.
 */
export type DitherMode = "auto" | "off" | "triangular" | "triangular_hp" | "shibata";
