// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DitherMode } from "./DitherMode";
import type { ExportFormat } from "./ExportFormat";

export type ExportConfig = { format: ExportFormat, 
/**
 * Bitrate for lossy formats (kbps).
 */
bitrate_kbps: number, 
/**
 * Bit depth for WAV/FLAC output (16 or 24).
 */
bit_depth: number, dest_dir: string, 
/**
 * File naming template, e.g. `{n} - {title}`.
 */
template: string, 
/**
 * Output sample rate; None = keep the session rate. High-quality
 * resampling happens in the encoder pipeline (aresample).
 */
target_sample_rate: number | null, 
/**
 * Dither policy for lossless depth reduction.
 */
dither: DitherMode, 
/**
 * Export a single Red Book image + cue sheet instead of one file per
 * track (forces 44.1 kHz / 16-bit / WAV, frame-aligned tracks).
 */
cd_image: boolean, };
