// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress event for ONE track. Exports run in parallel, so several tracks
 * progress at once; the display layer keeps one bar per track number and
 * uses `overall_progress`/`completed_tracks` for the global state.
 */
export type ExportProgress = { 
/**
 * Track number this event is about (1-based).
 */
track_number: number, track_count: number, track_title: string, 
/**
 * 0.0..=1.0 within this track.
 */
track_progress: number, 
/**
 * Tracks fully finished so far.
 */
completed_tracks: number, 
/**
 * 0.0..=1.0 across the whole export.
 */
overall_progress: number, };
