// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportFormat } from "./ExportFormat";

export type ExportConfig = { format: ExportFormat, 
/**
 * Bitrate for lossy formats (kbps).
 */
bitrate_kbps: number, 
/**
 * Bit depth for WAV output (16 or 24).
 */
bit_depth: number, dest_dir: string, 
/**
 * File naming template, e.g. `{n} - {title}`.
 */
template: string, };
