// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackMeasure } from "./TrackMeasure";

export type ExportedFile = { track_title: string, path: string, 
/**
 * Integrated loudness of the DELIVERED file (EBU R128), measured by
 * an analysis pass after encoding. None = analysis unavailable.
 */
lufs_i: number | null, lra: number | null, 
/**
 * Max true peak (dBTP) of the delivered file.
 */
true_peak_db: number | null, 
/**
 * Per-track breakdown when this single file holds several tracks
 * (CD image): each entry is measured on its cue segment.
 */
track_measures: Array<TrackMeasure>, };
