// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InputDeviceInfo = { name: string, 
/**
 * Channel count of the device's default (mix) input format.
 */
channels: number, sample_rate: number, is_default: boolean, 
/**
 * Human names of each input, index-aligned with 1..=channels
 * ("Input N" when the platform/driver names nothing).
 */
input_names: Array<string>, };
