// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InputDeviceInfo = { 
/**
 * Audio host exposing the device ("CoreAudio", "WASAPI", "ASIO", …).
 * On Windows a pro interface may appear under both WASAPI (often as
 * stereo endpoints) and ASIO (full channel count).
 */
host: string, name: string, 
/**
 * Channel count of the device's default (mix) input format.
 */
channels: number, sample_rate: number, is_default: boolean, 
/**
 * Human names of each input, index-aligned with 1..=channels
 * ("Input N" when the platform/driver names nothing).
 */
input_names: Array<string>, };
