// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Display state of one mix layer.
 */
export type LayerView = { id: number, 
/**
 * First source's file name.
 */
name: string, channels: number, duration_seconds: number, gain_db: number, muted: boolean, };
