// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MasteringPluginView } from "./MasteringPluginView";

/**
 * Display state of one mix layer.
 */
export type LayerView = { id: number, 
/**
 * Display name: the user's custom name, else the first source's file
 * name.
 */
name: string, 
/**
 * Always the first source's file name (tooltip after a rename).
 */
source_name: string, channels: number, duration_seconds: number, gain_db: number, muted: boolean, solo: boolean, collapsed: boolean, 
/**
 * This layer's insert chain (pre-fader, always active).
 */
inserts: Array<MasteringPluginView>, };
