// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginFormat } from "./PluginFormat";

/**
 * Display state of one mastering-chain plugin.
 */
export type MasteringPluginView = { id: number, component: string, name: string, bypass: boolean, format: PluginFormat, };
