// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Live loudness measurement of the master output (EBU R128 / BS.1770),
 * fed post-master-chain on the render thread. None = not enough signal
 * yet (or metering unavailable).
 */
export type MeterState = { lufs_m: number | null, lufs_s: number | null, lufs_i: number | null, lra: number | null, 
/**
 * Max-hold true peak in dBTP since the last reset.
 */
true_peak_db: number | null, };
