// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaybackState = { playing: boolean, position_seconds: number, 
/**
 * Output-device failure (no device, format refused…); playback is
 * silent while this is set. Display it — silence must never be mute.
 */
device_error: string | null, ready: boolean, };
