// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PluginFormat } from "./PluginFormat";

/**
 * One installed plugin, as listed to the frontend.
 */
export type PluginInfo = { 
/**
 * Component id: "aufx:xxxx:yyyy" (AU) or "vst3:<32 hex>" (VST3).
 */
id: string, name: string, manufacturer: string, format: PluginFormat, };
