// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AudioInfo } from "./AudioInfo";
import type { ExportConfig } from "./ExportConfig";
import type { LayerView } from "./LayerView";
import type { TrackInfo } from "./TrackInfo";

/**
 * Display snapshot sent to the frontend after every mutation.
 */
export type ProjectView = { audio: AudioInfo, layers: Array<LayerView>, tracks: Array<TrackInfo>, snap_to_zero: boolean, export_config: ExportConfig, project_path: string | null, 
/**
 * Backend-computed proposal for the next track title (may be empty).
 */
suggested_title: string, can_undo: boolean, can_redo: boolean, };
