// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordConfig = { 
/**
 * Device name; "" = system default input.
 */
device: string, 
/**
 * First device input to record, 1-based (e.g. 3 = input 3 → lane 1).
 */
first_input: number, 
/**
 * Number of consecutive inputs / files to record.
 */
layer_count: number, 
/**
 * Base folder; a fresh "Take N" subfolder is created inside.
 */
dest_dir: string, };
