// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordStatus = { recording: boolean, elapsed_seconds: number, sample_rate: number, 
/**
 * Per-lane linear peak since the previous status poll.
 */
levels: Array<number>, 
/**
 * Frames lost to ring overruns — must stay 0 on a healthy machine.
 */
dropped_frames: number, 
/**
 * The take folder being written.
 */
folder: string, error: string | null, };
