// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordLane = { 
/**
 * Device input feeding this lane, 1-based.
 */
input: number, 
/**
 * Layer name — becomes the file name (and thus the layer's display
 * name once loaded). "" = named after the input.
 */
name: string, };
