// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RecordLane } from "./RecordLane";

export type RecordConfig = { 
/**
 * Audio host of the device; "" = the platform's default host.
 */
host: string, 
/**
 * Device name; "" = system default input.
 */
device: string, 
/**
 * Lanes in file order; any input, any order, non-contiguous is fine.
 */
lanes: Array<RecordLane>, 
/**
 * Base folder; a fresh "Take N" subfolder is created inside.
 */
dest_dir: string, };
