// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A span of source audio, in samples. Used for region proposals and bulk adds.
 */
export type RegionSpan = { start: number, end: number, };
