// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipInfo } from "./ClipInfo";

/**
 * Scan result for one layer: its clips (sequential), channel count and
 * total length. Layers are time-synchronized: they all start at t = 0.
 */
export type ScannedLayer = { clips: Array<ClipInfo>, channels: number, duration_samples: number, };
