// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SilenceParams = { 
/**
 * Level under which a bucket counts as silent, in dBFS (e.g. -40).
 */
threshold_db: number, 
/**
 * Minimum silence length for a gap to separate two tracks.
 */
min_silence_ms: number, 
/**
 * Sound spans shorter than this are not proposed as tracks.
 */
min_track_seconds: number, };
