// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MasteringPluginView } from "./MasteringPluginView";

export type TrackInfo = { 
/**
 * Stable region id (rename/move/delete key).
 */
id: number, 
/**
 * 1-based track number, ordered by position in the file.
 */
number: number, title: string, start_sample: number, end_sample: number, duration_seconds: number, 
/**
 * Per-track layer gain overrides (dB), keyed by layer id (string).
 */
gain_overrides: Record<string, number>, mute_overrides: Record<string, boolean>, solo_overrides: Record<string, boolean>, 
/**
 * Resolved linear volume of every layer for THIS track (session gains,
 * mutes and solos with the track's overrides applied). Index-aligned
 * with the layer list; this is exactly what export and playback use.
 */
layer_volumes: Array<number>, 
/**
 * Normalized ISRC ("" = none).
 */
isrc: string, 
/**
 * This track's insert chain (master-bus position, active in its span).
 */
inserts: Array<MasteringPluginView>, };
