// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Fully resolved tag values for ONE exported track (macros expanded,
 * numbering computed). This is what gets written to the file.
 */
export type TrackTags = { title: string, artist: string, album: string, album_artist: string, date: string, genre: string, comment: string, 
/**
 * Track number WITHIN its disc (restarts at 1 on each disc).
 */
track: number, 
/**
 * Number of tracks on this track's disc.
 */
track_total: number, disc: number, disc_total: number, };
