// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackInfo = { 
/**
 * Stable region id (rename/move/delete key).
 */
id: number, 
/**
 * 1-based track number, ordered by position in the file.
 */
number: number, title: string, start_sample: number, end_sample: number, duration_seconds: number, };
