// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TrackMeasure = { number: number, title: string, lufs_i: number | null, lra: number | null, true_peak_db: number | null, };
